###
POST http://localhost:8080/daily-bugle/api/users/register
Content-Type: application/json

{
  "email": "journalist@test.com",
  "password": "1234",
  "displayName": "Peter Parker",
  "role": "JOURNALIST"
}


###
POST http://localhost:8080/daily-bugle/api/users/register
Content-Type: application/json

{
  "email": "reader@test.com",
  "password": "1234",
  "displayName": "Mary Jane",
  "role": "READER"
}

###
POST http://localhost:8080/daily-bugle/api/users/login
Content-Type: application/json

{
  "email": "journalist@test.com",
  "password": "1234"
}

###
POST http://localhost:8080/daily-bugle/api/users/login
Content-Type: application/json

{
  "email": "reader@test.com",
  "password": "1234"
}

###
POST http://localhost:8080/daily-bugle/api/articles
Content-Type: application/json
X-User-Id: 1

{
  "title": "Daily Bugle Breaking News",
  "synopsis": "Something big happened",
  "content": "Full article content here..."
}

###
POST http://localhost:8080/daily-bugle/api/comments
Content-Type: application/json
X-User-Id: 2

{
  "articleId": 1,
  "content": "Great article!"
}

###
POST http://localhost:8080/daily-bugle/api/ratings
Content-Type: application/json
X-User-Id: 2

{
  "articleId": 1,
  "value": 5
}

###
POST http://localhost:8080/daily-bugle/api/ratings
Content-Type: application/json
X-User-Id: 2

{
  "articleId": 1,
  "value": 4
}

###
GET http://localhost:8080/daily-bugle/api/users/2

###
GET http://localhost:8080/daily-bugle/api/users/1